config/routes.rb
Rails.application.routes.draw do
  resources :tunes do
    collection do
      post :playlist
      get :list
    end
    member do
      get :search
    end
  end

  root to: 'tunes#index'

end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :tunes
  mount_uploader :image, ImageUploader
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :tunes
end

app/models/tune.rb
class Tune < ActiveRecord::Base
  belongs_to :artist
  belongs_to :album
  accepts_nested_attributes_for :artist
  accepts_nested_attributes_for :album
  mount_uploader :mp3, Mp3Uploader

  def save_info
    title, name, year = '', '', 0
    Mp3Info.open(mp3.path) do |file|
      file.tag.each do |key, val|
        case key
        when 'title' then
          self.title = val
        when 'album' then
          title = val
        when 'artist' then
          name = val
        when 'year' then
          year = val
        when 'tracknum' then
          self.tracknum = val
        when 'genre_s' then
          self.genre = val
        end
      end
      # ジャケット画像用検索クエリ
      # query = title + ' ' + name
      query = title
      save_album(title, year, query)
      save_artist(name)
    end
    save
  end

  def save_artist(name)
    res = Artist.find_by(name: name)
    if res == nil
      new = Artist.create(name: name)
      res = new
    end
    self.artist_id = res.id
  end

  def save_album(title, year, query)
    res = Album.find_by(title: title, year: year)
    if res == nil
      # ジャケット画像のurlを取得
      link = ScrapeJacket.rakuten_get_link(query, 1)
      # 文字化け等でlinkが取得できなかった場合，img_urlは空
      img_url = link != nil ? ScrapeJacket.rakuten_get_cdjacket(link) : ''

      new = Album.create(title: title, year: year, remote_image_url: img_url.first)
      res = new
    end
    self.album_id = res.id
  end

  def update_info(params)
    name = params[:artist_attributes][:name]
    title = params[:album_attributes][:title]
    year = params[:album_attributes][:year]
    save_artist(name)
    save_album(title, year, title)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tunes_controller.rb
class TunesController < ApplicationController
  before_action :set_tune, only: [:show, :edit, :update, :destroy]

  # GET /tunes
  # GET /tunes.json
  def index
    @tunes = Tune.all
    @lists = []
    @tunes.each do |tune|
      @lists << { src: tune.mp3.url, title: tune.title }
    end
    @lists.join(', ')
  end

  # GET /tunes/1
  # GET /tunes/1.json
  def show
  end

  # GET /tunes/new
  def new
    @tune = Tune.new
  end

  # GET /tunes/1/edit
  def edit
  end

  # POST /tunes
  # POST /tunes.json
  def create
    @tune = Tune.new(tune_params)

    respond_to do |format|
      if @tune.save_info
        format.html { redirect_to @tune, notice: 'Tune was successfully created.' }
        format.json { render :show, status: :created, location: @tune }
      else
        format.html { render :new }
        format.json { render json: @tune.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tunes/1
  # PATCH/PUT /tunes/1.json
  def update
    @tune.update_info(params[:tune]) # 変更したartistとalbumが既に登録済みかチェック
    # 変更したジャケット画像の更新
    @tune.album.remote_image_url = params[:jacket] if params[:jacket].present?
    respond_to do |format|
      if @tune.update(tune_params)
        format.html { redirect_to @tune, notice: 'Tune was successfully updated.' }
        format.json { render :show, status: :ok, location: @tune }
      else
        format.html { render :edit }
        format.json { render json: @tune.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tunes/1
  # DELETE /tunes/1.json
  def destroy
    @tune.destroy
    respond_to do |format|
      format.html { redirect_to tunes_url, notice: 'Tune was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def list
    respond_to do |format|
      format.html
      format.json { render json: TunesDatatable.new(params) }
    end
  end

  def search
    @album = Album.find_by(id: params[:album_id])
    respond_to do |format|
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tune
      @tune = Tune.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tune_params
      params.require(:tune).permit(
        :mp3,
        :title,
        :genre,
        :remarks,
        #artist_attributes: [:name],
        #album_attributes: [:title, :year]
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def audio_tag_multiple(sources)
    content_tag(:audio) do
      sources.map do |source|
        safe_concat(tag :source, source, true)
      end
    end
  end
end

app/helpers/tunes_helper.rb
module TunesHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Discography
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js'
    = csrf_meta_tags
  body
    = yield

app/views/tunes/_editform.html.slim
= form_for(@tune) do |f|
  - if @tune.errors.any?
    #error_explanation
      h2
        = pluralize(@tune.errors.count, "error")
        |  prohibited this tune from being saved:
      ul
        - @tune.errors.full_messages.each do |message|
          li
            = message
  .field
    = f.label :title
    br
    = f.text_field :title
  /.field
    = label :artist, :name
    br
    = text_field :artist, :name
  /.field
    = f.label :genre
    br
    = f.text_field :genre
  /.field
    = f.label :mp3
    br
    = f.file_field :mp3
  /.field
    = f.label :image
    br
    = f.file_field :image
  .actions
    = f.submit

app/views/tunes/_form.html.slim
= form_for(@tune) do |f|
  - if @tune.errors.any?
    #error_explanation
      h2
        = pluralize(@tune.errors.count, "error")
        |  prohibited this tune from being saved:
      ul
        - @tune.errors.full_messages.each do |message|
          li
            = message
  /.field
    = f.label :title
    br
    = f.text_field :title
  .field
    = f.label :mp3
    br
    = f.file_field :mp3
  /.field
    = f.label :image
    br
    = f.file_field :image
  .actions
    = f.submit

app/views/tunes/_search_image.html.slim
- link = ScrapeJacket.rakuten_get_link(val.title, 5)
- img_urls = link != nil ? ScrapeJacket.rakuten_get_cdjacket(link) : ''
- img_urls.each_with_index do |img, index|
  = radio_button_tag 'jacket', img
  = image_tag img, size: '100x100'

app/views/tunes/_tuneform.html.slim
= form_for(@tune) do |f|
  - if @tune.errors.any?
    #error_explanation
      h2
        = pluralize(@tune.errors.count, "error")
        |  prohibited this tune from being saved:
      ul
        - @tune.errors.full_messages.each do |message|
          li
            = message
  .field
    | Music title
    br
    = f.text_field :title
  .field
    | Genre
    br
    = f.text_field :genre
  .field
    | Comment
    br
    = f.text_field :remarks
  = f.fields_for :artist do |ar|
    .field
      | Artist name
      br
      = ar.text_field :name
  = f.fields_for :album do |al|
    .field
      | Album title
      br
      = al.text_field :title
    .field
      | Year
      br
      = al.text_field :year
    .field
      | Album jacket
      br
      = image_tag @tune.album.image.url, size: '200x200'
    .field
      /= button_tag 'Search Image', { action: :search_image }, { remote: true }
      /#search_reslut
      /= render 'search_image', val: @tune.album.title
      = link_to 'Search Image', search_tune_path(album_id: @tune.album_id), remote: true
      #show
  .actions
    = f.submit

app/views/tunes/edit.html.slim
h1
  | Editing Tune
= render 'tuneform'
= link_to 'Show', @tune
|  | 
= link_to 'Back', tunes_path

app/views/tunes/index.html.slim
= javascript_include_tag 'mep-feature-playlist.js'
= stylesheet_link_tag 'mep-feature-playlist.css'
p#notice
  = notice
h1
  | Listing Tunes
table#datatables.table.table-striped.table-bordered
  thead
    tr
      th
        | 
      th
        | Image
      th
        | Title
      th
        | Track
      th
        | Album
      th
        | Artist
      th
        | Genre
      /th
        | show
      /th
        | edit
      /th
        | des
      th
        | 
  tbody
    - @tunes.each_with_index do |tune, index|
      tr
        td
          = check_box_tag 'tune', index
        td
          = image_tag(tune.album.image.url, size: "32x32")
        td
          = tune.title
        td
          = tune.tracknum
        td
          = tune.album.title
        td
          = tune.artist.name
        td
          = tune.genre
        /td
          = link_to 'Show', tune
        td
          = link_to 'Edit', edit_tune_path(tune)
        /td
          = link_to 'Destroy', tune, method: :delete, data: { confirm: 'Are you sure?' }
br
div style='text-align:center'
  = link_to 'Add Playlist'
  span style='margin-left:100px'
    = link_to 'New Tune', new_tune_path
br
= audio_tag_multiple(@lists)

app/views/tunes/list.html.slim
table#tunes.table.table-striped.table-bordered
  thead
    tr
      th
        | Name
      th
        | Artist
      th
        | mp3
  tbody

app/views/tunes/new.html.slim
h1
  | New Tune
= render 'form'
= link_to 'Back', tunes_path

app/views/tunes/search.js.erb
$('#show').html("<%= escape_javascript(render partial: 'search_image', locals: { val: @album }) %>");

app/views/tunes/show.html.slim
p#notice
  = notice
/p
  strong
    | Title:
  = @tune.title
/p
  strong
    | Artist:
  = @tune.artist
/p
  strong
    | Genre:
  = @tune.genre
= link_to 'Edit', edit_tune_path(@tune)
|  | 
= link_to 'Back', tunes_path